### ISSUE TITLE
Do better alignment for the leftsidebar's accordion data.

### ISSUE THREAD

**Issue by ArshErgon** [ArshErgon/ResumeWizard#10]
As the input form inside the leftsidebar's accordion there are many fields which are out of place or need a better margin.

this issue is quite easy, as only the basic knowledge of css is required, marking it as `good-first-issue`

**Comment by vishalpawarR** [comment]
@ArshErgon if you can explain the issue or point to the specific issue with proper screenshot may be I can try to fix this issue.

**Comment by ArshErgon** [comment]
hey @vishalpawarR yeah, sure
![Screenshot from 2023-06-14 08-04-03](https://github.com/ArshErgon/ResumeWizard/assets/40994679/3a5aa28f-59ad-43eb-aafb-f738317c450f)

As you can see Name, Role, Socials etc doesn't have a margin-top or bottom which separate them, and the textarea as its not align properly. The project is using `daisyUI` so a little knowledge of CSS and TailWindCSS will help you alot.

**Comment by vishalpawarR** [comment]
@ArshErgon If you like this solution do let me know if I can continue fixing the issues?
![image](https://github.com/ArshErgon/ResumeWizard/assets/55725885/270018de-414c-44f2-a628-1d5e082d9406)
I have taken the name and input in next line I think it is looking good. If you agree I can fix and open a pull a request
![image](https://github.com/ArshErgon/ResumeWizard/assets/55725885/42fdc4ea-c83b-4d42-9a66-5eb531b8ba23)

**Comment by ArshErgon** [comment]
@vishalpawarR I love this.

**Comment by vishalpawarR** [comment]
@ArshErgon Thank you. I have made the changes and Created a PR please have a look at it and refer the screenshot below:
![screencapture-127-0-0-1-5173-2023-06-14-14_07_43](https://github.com/ArshErgon/ResumeWizard/assets/55725885/e609fbfc-1d3a-4827-a7a9-0e5cf59feaae)

**Comment by vishalpawarR** [comment]
@ArshErgon Hope I was helpful in adding my comments

**Comment by ArshErgon** [comment]
@vishalpawarR I respect every PR which comes on my repos, even comments, issues, or a simple README.md update, no matter how much experience a person has while doing open source contribution he/she will still get confused in some point, I myself also had gotten into a point where many of my working PRs close by moderator or simply deleted then rewritten by the mod by themselves as like they solved it.

Your time and effort I respect that, your PR was great but because its not sync to the master branch I could not accept it, there were conflicts, conflicts could be remove if you had create a new updated branch with the desired changes, I waited alot for your re-updated PR but I couldn't get it.
Anyway, I will be starting more `good-first-issues` hope there we both can learn something from each other, and you can get more hands on open source contribution. 
See you there!
> ArshErgon
