### ISSUE TITLE
Update the placeholder text inside the input fields

### ISSUE THREAD

**Issue by vishalpawarR** [ArshErgon/ResumeWizard#16]
@ArshErgon Hey can we Replace the word random with the more meaningful word inside the input placeholder may be I can help you with it? Please refer the below screenshots and Kindly suggest Any specific words you want to replace it or I can suggest some words here!

Screenshots:
- ![image](https://github.com/ArshErgon/ResumeWizard/assets/55725885/8ba2fc11-699b-45d9-af83-3fe2d4464a31)
- ![image](https://github.com/ArshErgon/ResumeWizard/assets/55725885/5ecf1e82-5a70-4f32-af72-807937dc39af)
- ![image](https://github.com/ArshErgon/ResumeWizard/assets/55725885/ff56584f-c3d5-4b46-82b7-f6413a3e948e)

**Comment by ArshErgon** [comment]
hi @vishalpawarR  yeah, those placeholders are basically dummyData, if you have better dummyData suggestion give a PR.
